from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, Optional

from loguru import logger

if TYPE_CHECKING:
    from openai.types.chat.chat_completion import ChatCompletion
    from openai.types.responses.response import Response


class TokenLimitExceededError(Exception):
    """Raised when the output token limit is exceeded."""

    def __init__(self, current_tokens: int, limit: int, message: Optional[str] = None):
        self.current_tokens = current_tokens
        self.limit = limit
        if message is None:
            message = f"Token limit exceeded: {current_tokens} tokens generated, limit is {limit}"
        super().__init__(message)


class LLMClient(ABC):
    """Abstract base class for LLM providers."""

    DEFAULT_TOKEN_LIMIT = 1_000_000  # 1 million tokens

    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
    ) -> None:
        """Initialize LLM client with token tracking.

        Args:
            model: The model identifier.
            max_output_tokens: Maximum number of output tokens allowed.
                             Defaults to 1 million if None.
            enable_token_limit: Whether to enforce the token limit.
                              If False, tokens are still counted but no limit is enforced.
        """
        self.model = model
        self._total_output_tokens = 0
        self._max_output_tokens = max_output_tokens or self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enable_token_limit

        logger.debug(
            f"Initialized LLM client: model={model}, "
            f"max_tokens={self._max_output_tokens}, "
            f"limit_enabled={enable_token_limit}"
        )

    @abstractmethod
    def generate(self, prompt: str, **kwargs: Any) -> str:
        """Generate text from the model."""
        pass

    def _estimate_tokens(self, text: str) -> int:
        """Estimate the number of tokens in the given text.

        Uses the approximation: 1 token ≈ 4 characters.

        Args:
            text: The text to estimate tokens for.

        Returns:
            Estimated number of tokens.
        """
        return len(text) // 4

    def _add_output_tokens(self, tokens: int) -> None:
        """Add the estimated tokens from a response to the total count.

        Args:
            tokens: The number of tokens generated.
        Raises:
            TokenLimitExceededError: If the token limit is enabled and would be exceeded.
        """
        new_total = self._total_output_tokens + tokens

        # Check if adding these tokens would exceed the limit
        if self._enable_token_limit and new_total > self._max_output_tokens:
            logger.error(
                f"Token limit exceeded: adding {tokens} tokens would exceed limit of "
                f"{self._max_output_tokens} (current: {self._total_output_tokens})"
            )
            raise TokenLimitExceededError(
                current_tokens=self._total_output_tokens,
                limit=self._max_output_tokens,
                message=f"Adding {tokens} tokens would exceed limit of {self._max_output_tokens} "
                f"(current: {self._total_output_tokens}, new total would be: {new_total})",
            )

        self._total_output_tokens = new_total

        logger.trace(
            f"Added {tokens} tokens, total: {self._total_output_tokens}/{self._max_output_tokens}"
        )

    @property
    def total_output_tokens(self) -> int:
        """Get the total number of output tokens generated by this client.

        Returns:
            Total number of output tokens.
        """
        return self._total_output_tokens

    def reset_token_count(self) -> None:
        """Reset the output token counter to zero."""
        old_count = self._total_output_tokens
        self._total_output_tokens = 0
        logger.info(f"Reset token count from {old_count} to 0")

    @property
    def max_output_tokens(self) -> int:
        """Get the maximum number of output tokens allowed.

        Returns:
            Maximum number of output tokens.
        """
        return self._max_output_tokens

    @property
    def is_token_limit_enabled(self) -> bool:
        """Check if token limit enforcement is enabled.

        Returns:
            True if token limit is enforced, False otherwise.
        """
        return self._enable_token_limit

    @property
    def tokens_remaining(self) -> int:
        """Get the number of tokens remaining before hitting the limit.

        Returns:
            Number of tokens remaining, or -1 if limit is disabled.
        """
        if not self._enable_token_limit:
            return -1
        return max(0, self._max_output_tokens - self._total_output_tokens)

    def set_token_limit(
        self, max_tokens: Optional[int] = None, enabled: bool = True
    ) -> None:
        """Configure the token limit settings.

        Args:
            max_tokens: New maximum token limit. If None, uses the default limit.
            enabled: Whether to enable token limit enforcement.
        """
        old_limit = self._max_output_tokens
        old_enabled = self._enable_token_limit

        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        else:
            self._max_output_tokens = self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enabled

        logger.info(
            f"Updated token limit: {old_limit} → {self._max_output_tokens}, "
            f"enabled: {old_enabled} → {enabled}"
        )

    def disable_token_limit(self) -> None:
        """Disable token limit enforcement while keeping the counter active."""
        self._enable_token_limit = False
        logger.info("Disabled token limit enforcement")

    def enable_token_limit(self, max_tokens: Optional[int] = None) -> None:
        """Enable token limit enforcement.

        Args:
            max_tokens: Optional new maximum token limit. If None, keeps current limit.
        """
        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        self._enable_token_limit = True
        logger.info(
            f"Enabled token limit enforcement: max_tokens={self._max_output_tokens}"
        )


# ----------------------------
# OpenAI Client Implementation
# ----------------------------
class OpenAIChatClient(LLMClient):
    """
    OpenAI Client using the Chat Completions API
    """

    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        from openai import OpenAI

        self.client = OpenAI(**kwargs)
        logger.debug(f"Initialized OpenAIChatClient with model: {model}")

    def generate(self, prompt: str, **kwargs: Any) -> str:
        logger.debug(f"OpenAIChatClient generating with model: {self.model}")
        logger.trace(f"Prompt (first 200 chars): {prompt[:200]}...")

        response: ChatCompletion = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            **kwargs,
        )
        content = response.choices[0].message.content
        if content is None:
            logger.error("OpenAI response content is None")
            raise ValueError("OpenAI response content is None")

        result = str(content)
        logger.debug(f"Generated {len(result)} characters")
        logger.trace(f"Response (first 200 chars): {result[:200]}...")
        self._add_output_tokens(self._estimate_tokens(result))
        return result


# ----------------------------
# OpenAI Codex Client Implementation (using Response API)
# ----------------------------
class OpenAIClient(LLMClient):
    """
    OpenAI Client using the Response API
    """

    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
        reasoning_effort: str | None = "minimal",
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        from openai import OpenAI

        self.reasoning_effort = reasoning_effort
        self.client = OpenAI(**kwargs)
        logger.debug(
            f"Initialized OpenAIClient with model: {model}, "
            f"reasoning_effort: {reasoning_effort}"
        )

    def _add_openai_output_tokens(self, response: "Response") -> None:
        """Add output tokens from OpenAI Response API response.

        Args:
            response: The OpenAI Response API response object.
        """
        if (
            hasattr(response, "usage")
            and response.usage is not None
            and hasattr(response.usage, "output_tokens")
        ):
            output_tokens = response.usage.output_tokens
            return super()._add_output_tokens(output_tokens)
        else:
            logger.warning(
                "Response object does not have usage.output_tokens; "
                "cannot track output tokens accurately."
                "using approximate character-based estimation instead."
            )

            return super()._add_output_tokens(
                self._estimate_tokens(response.output_text)
            )

    def generate(self, prompt: str, **kwargs: Any) -> str:
        # Allow overriding reasoning effort for this specific call
        reasoning_effort = kwargs.pop("reasoning_effort", self.reasoning_effort)

        logger.debug(
            f"OpenAIClient generating with model: {self.model}, "
            f"reasoning_effort: {reasoning_effort}"
        )
        logger.trace(f"Prompt (first 200 chars): {prompt[:200]}...")

        response: "Response" = self.client.responses.create(
            model=self.model,
            input=prompt,
            reasoning={"effort": reasoning_effort},
            **kwargs,
        )

        content = response.output_text if hasattr(response, "output_text") else None

        if content is None:
            logger.error("OpenAI Response API response content is None")
            raise ValueError("OpenAI Codex response content is None")

        result = str(content)
        logger.debug(f"Generated {len(result)} characters")
        logger.trace(f"Response (first 200 chars): {result[:200]}...")

        self._add_openai_output_tokens(response)
        return result

    def set_reasoning_effort(self, reasoning_effort: str) -> None:
        """Set the reasoning effort level for future generations.

        Args:
            reasoning_effort: The reasoning effort level to use.
                            Common values: 'minimal', 'low', 'medium', 'high'
        """
        old_effort = self.reasoning_effort
        self.reasoning_effort = reasoning_effort
        logger.info(f"Updated reasoning effort: {old_effort} → {reasoning_effort}")

    def get_reasoning_effort(self) -> str | None:
        """Get the current reasoning effort level.

        Returns:
            The current reasoning effort level.
        """
        return self.reasoning_effort


# ----------------------------
# Ollama Client Implementation
# ----------------------------
class OllamaClient(LLMClient):
    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = False,
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        import ollama

        self.ollama = ollama
        logger.debug(f"Initialized OllamaClient with model: {model}")

    def generate(self, prompt: str, **kwargs: Any) -> str:
        logger.debug(f"OllamaClient generating with model: {self.model}")
        logger.trace(f"Prompt (first 200 chars): {prompt[:200]}...")

        response = self.ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            **kwargs,
        )
        content = response["message"]["content"]
        if not isinstance(content, str):
            logger.error(f"Expected string content, got {type(content)}")
            raise ValueError(f"Expected string content, got {type(content)}")

        logger.debug(f"Generated {len(content)} characters")
        logger.trace(f"Response (first 200 chars): {content[:200]}...")
        self._add_output_tokens(self._estimate_tokens(content))
        return content


# ----------------------------
# Factory Function (Optional)
# ----------------------------
def create_llm_client(
    provider: str,
    model: str,
    max_output_tokens: Optional[int] = None,
    enable_token_limit: Optional[bool] = None,
    reasoning_effort: Optional[str] = None,
    **kwargs: Any,
) -> LLMClient:
    """Create an LLM client with the specified provider and configuration.

    Args:
        provider: The LLM provider ('openai', 'openai-codex', or 'ollama').
        model: The model identifier.
        max_output_tokens: Maximum number of output tokens allowed (default: 1M).
        enable_token_limit: Whether to enforce the token limit. If None, uses provider defaults:
                          - OpenAI clients: True (limits enabled by default)
                          - Ollama clients: False (limits disabled by default)
        reasoning_effort: The reasoning effort level for OpenAI Response API models.
                         Common values: 'minimal', 'low', 'medium', 'high'.
                         Defaults to 'minimal'. Only applies to 'openai' provider.
        **kwargs: Additional provider-specific arguments.

    Returns:
        Configured LLM client instance.

    Raises:
        ValueError: If the provider is not supported.
    """
    provider = provider.lower()

    logger.info(f"Creating LLM client: provider={provider}, model={model}")

    # Extract special parameters from kwargs to pass to constructors
    client_kwargs = {
        k: v
        for k, v in kwargs.items()
        if k not in ["max_output_tokens", "enable_token_limit", "reasoning_effort"]
    }

    client: LLMClient
    if provider == "openai":
        # OpenAI default: token limits enabled
        limit_enabled = True if enable_token_limit is None else enable_token_limit
        client = OpenAIClient(
            model, max_output_tokens, limit_enabled, reasoning_effort, **client_kwargs
        )
    elif provider == "openai-chat":
        # OpenAI Codex default: token limits enabled
        limit_enabled = True if enable_token_limit is None else enable_token_limit
        client = OpenAIChatClient(
            model, max_output_tokens, limit_enabled, **client_kwargs
        )
    elif provider == "ollama":
        # Ollama default: token limits disabled
        limit_enabled = False if enable_token_limit is None else enable_token_limit
        client = OllamaClient(model, max_output_tokens, limit_enabled, **client_kwargs)
    else:
        logger.error(f"Unsupported provider: {provider}")
        raise ValueError(f"Unsupported provider: {provider}")

    logger.info(f"Successfully created {client.__class__.__name__}")
    return client
