provider: "openai"
model: "openai/gpt-oss-120b"
api_key: "${GROQ_API_KEY}"
base_url: "https://api.groq.com/openai/v1"

# Experiment Parameters
max_output_tokens: 100_000_000
workers: 32


generation_params:
  reasoning_effort: "low"
  temperature: 1.0
  top_p: 1.0


