"""Base classes for LLM clients."""

from abc import ABC, abstractmethod
from typing import Any, Optional

from loguru import logger

from .exceptions import TokenLimitExceededError


class LLMClient(ABC):
    """Abstract base class for LLM providers."""

    DEFAULT_TOKEN_LIMIT = 1_000_000  # 1 million tokens

    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
        workers: int = 1,
    ) -> None:
        """Initialize LLM client with token tracking.

        Args:
            model: The model identifier.
            max_output_tokens: Maximum number of output tokens allowed.
                             Defaults to 1 million if None.
            enable_token_limit: Whether to enforce the token limit.
                              If False, tokens are still counted but no limit is enforced.
            workers: Maximum number of concurrent requests this client can handle.
        """
        self.model = model
        self.workers = workers
        self._total_input_tokens = 0
        self._total_output_tokens = 0
        self._max_output_tokens = max_output_tokens or self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enable_token_limit

        logger.debug(
            f"Initialized LLM client: model={model}, "
            f"max_tokens={self._max_output_tokens}, "
            f"limit_enabled={enable_token_limit}"
        )

    @abstractmethod
    def generate(self, prompt: Any, **kwargs: Any) -> str:
        """Generate text from the model."""
        pass

    def _estimate_tokens(self, text: str) -> int:
        """Estimate the number of tokens in the given text.

        Uses the approximation: 1 token ≈ 4 characters.

        Args:
            text: The text to estimate tokens for.

        Returns:
            Estimated number of tokens.
        """
        return len(text) // 4

    def _add_input_tokens(self, tokens: int) -> None:
        """Add input tokens to the total count.

        Args:
            tokens: The number of input tokens.
        """
        self._total_input_tokens += tokens
        logger.trace(f"Added {tokens} input tokens, total: {self._total_input_tokens}")

    def _add_output_tokens(self, tokens: int) -> None:
        """Add the estimated tokens from a response to the total count.

        Args:
            tokens: The number of tokens generated.
        Raises:
            TokenLimitExceededError: If the token limit is enabled and would be exceeded.
        """
        new_total = self._total_output_tokens + tokens

        # Check if adding these tokens would exceed the limit
        if self._enable_token_limit and new_total > self._max_output_tokens:
            logger.error(
                f"Token limit exceeded: adding {tokens} tokens would exceed limit of "
                f"{self._max_output_tokens} (current: {self._total_output_tokens})"
            )
            raise TokenLimitExceededError(
                current_tokens=self._total_output_tokens,
                limit=self._max_output_tokens,
                message=f"Adding {tokens} tokens would exceed limit of {self._max_output_tokens} "
                f"(current: {self._total_output_tokens}, new total would be: {new_total})",
            )

        self._total_output_tokens = new_total

        logger.trace(
            f"Added {tokens} tokens, total: {self._total_output_tokens}/{self._max_output_tokens}"
        )

    @property
    def total_input_tokens(self) -> int:
        """Get the total number of input tokens.

        Returns:
            Total number of input tokens.
        """
        return self._total_input_tokens

    @property
    def total_output_tokens(self) -> int:
        """Get the total number of output tokens generated by this client.

        Returns:
            Total number of output tokens.
        """
        return self._total_output_tokens

    @property
    def total_tokens(self) -> int:
        """Get the combined total of input and output tokens.

        Returns:
            Total number of tokens.
        """
        return self._total_input_tokens + self._total_output_tokens

    def reset_token_count(self) -> None:
        """Reset both input and output token counters to zero."""
        old_input = self._total_input_tokens
        old_output = self._total_output_tokens
        self._total_input_tokens = 0
        self._total_output_tokens = 0
        logger.info(
            f"Reset token counts: input ({old_input} → 0), output ({old_output} → 0)"
        )

    @property
    def max_output_tokens(self) -> int:
        """Get the maximum number of output tokens allowed.

        Returns:
            Maximum number of output tokens.
        """
        return self._max_output_tokens

    @property
    def is_token_limit_enabled(self) -> bool:
        """Check if token limit enforcement is enabled.

        Returns:
            True if token limit is enforced, False otherwise.
        """
        return self._enable_token_limit

    @property
    def tokens_remaining(self) -> int:
        """Get the number of tokens remaining before hitting the limit.

        Returns:
            Number of tokens remaining, or -1 if limit is disabled.
        """
        if not self._enable_token_limit:
            return -1
        return max(0, self._max_output_tokens - self._total_output_tokens)

    def set_token_limit(
        self, max_tokens: Optional[int] = None, enabled: bool = True
    ) -> None:
        """Configure the token limit settings.

        Args:
            max_tokens: New maximum token limit. If None, uses the default limit.
            enabled: Whether to enable token limit enforcement.
        """
        old_limit = self._max_output_tokens
        old_enabled = self._enable_token_limit

        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        else:
            self._max_output_tokens = self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enabled

        logger.info(
            f"Updated token limit: {old_limit} → {self._max_output_tokens}, "
            f"enabled: {old_enabled} → {enabled}"
        )

    def disable_token_limit(self) -> None:
        """Disable token limit enforcement while keeping the counter active."""
        self._enable_token_limit = False
        logger.info("Disabled token limit enforcement")

    def enable_token_limit(self, max_tokens: Optional[int] = None) -> None:
        """Enable token limit enforcement.

        Args:
            max_tokens: Optional new maximum token limit. If None, keeps current limit.
        """
        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        self._enable_token_limit = True
        logger.info(
            f"Enabled token limit enforcement: max_tokens={self._max_output_tokens}"
        )
