from abc import ABC, abstractmethod
from typing import Any, Optional


class TokenLimitExceededError(Exception):
    """Raised when the output token limit is exceeded."""

    def __init__(self, current_tokens: int, limit: int, message: Optional[str] = None):
        self.current_tokens = current_tokens
        self.limit = limit
        if message is None:
            message = f"Token limit exceeded: {current_tokens} tokens generated, limit is {limit}"
        super().__init__(message)


class LLMClient(ABC):
    """Abstract base class for LLM providers."""

    DEFAULT_TOKEN_LIMIT = 1_000_000  # 1 million tokens

    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
    ) -> None:
        """Initialize LLM client with token tracking.

        Args:
            model: The model identifier.
            max_output_tokens: Maximum number of output tokens allowed.
                             Defaults to 1 million if None.
            enable_token_limit: Whether to enforce the token limit.
                              If False, tokens are still counted but no limit is enforced.
        """
        self.model = model
        self._total_output_tokens = 0
        self._max_output_tokens = max_output_tokens or self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enable_token_limit

    @abstractmethod
    def generate(self, prompt: str, **kwargs: Any) -> str:
        """Generate text from the model."""
        pass

    def _estimate_tokens(self, text: str) -> int:
        """Estimate the number of tokens in the given text.

        Uses the approximation: 1 token ≈ 4 characters.

        Args:
            text: The text to estimate tokens for.

        Returns:
            Estimated number of tokens.
        """
        return len(text) // 4

    def _add_output_tokens(self, response: str) -> None:
        """Add the estimated tokens from a response to the total count.

        Args:
            response: The generated response text.

        Raises:
            TokenLimitExceededError: If the token limit is enabled and would be exceeded.
        """
        tokens = self._estimate_tokens(response)
        new_total = self._total_output_tokens + tokens

        # Check if adding these tokens would exceed the limit
        if self._enable_token_limit and new_total > self._max_output_tokens:
            raise TokenLimitExceededError(
                current_tokens=self._total_output_tokens,
                limit=self._max_output_tokens,
                message=f"Adding {tokens} tokens would exceed limit of {self._max_output_tokens} "
                f"(current: {self._total_output_tokens}, new total would be: {new_total})",
            )

        self._total_output_tokens = new_total

    @property
    def total_output_tokens(self) -> int:
        """Get the total number of output tokens generated by this client.

        Returns:
            Total number of output tokens.
        """
        return self._total_output_tokens

    def reset_token_count(self) -> None:
        """Reset the output token counter to zero."""
        self._total_output_tokens = 0

    @property
    def max_output_tokens(self) -> int:
        """Get the maximum number of output tokens allowed.

        Returns:
            Maximum number of output tokens.
        """
        return self._max_output_tokens

    @property
    def is_token_limit_enabled(self) -> bool:
        """Check if token limit enforcement is enabled.

        Returns:
            True if token limit is enforced, False otherwise.
        """
        return self._enable_token_limit

    @property
    def tokens_remaining(self) -> int:
        """Get the number of tokens remaining before hitting the limit.

        Returns:
            Number of tokens remaining, or -1 if limit is disabled.
        """
        if not self._enable_token_limit:
            return -1
        return max(0, self._max_output_tokens - self._total_output_tokens)

    def set_token_limit(
        self, max_tokens: Optional[int] = None, enabled: bool = True
    ) -> None:
        """Configure the token limit settings.

        Args:
            max_tokens: New maximum token limit. If None, uses the default limit.
            enabled: Whether to enable token limit enforcement.
        """
        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        else:
            self._max_output_tokens = self.DEFAULT_TOKEN_LIMIT
        self._enable_token_limit = enabled

    def disable_token_limit(self) -> None:
        """Disable token limit enforcement while keeping the counter active."""
        self._enable_token_limit = False

    def enable_token_limit(self, max_tokens: Optional[int] = None) -> None:
        """Enable token limit enforcement.

        Args:
            max_tokens: Optional new maximum token limit. If None, keeps current limit.
        """
        if max_tokens is not None:
            self._max_output_tokens = max_tokens
        self._enable_token_limit = True


# ----------------------------
# OpenAI Client Implementation
# ----------------------------
class OpenAIClient(LLMClient):
    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        from openai import OpenAI

        self.client = OpenAI(**kwargs)

    def generate(self, prompt: str, **kwargs: Any) -> str:
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            **kwargs,
        )
        content = response.choices[0].message.content
        if content is None:
            raise ValueError("OpenAI response content is None")

        result = str(content)
        self._add_output_tokens(result)
        return result


# ----------------------------
# OpenAI Codex Client Implementation (using Response API)
# ----------------------------
class OpenAICodexClient(LLMClient):
    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = True,
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        from openai import OpenAI

        self.client = OpenAI(**kwargs)

    def generate(self, prompt: str, **kwargs: Any) -> str:
        response = self.client.responses.create(
            model=self.model,
            input=prompt,
            **kwargs,
        )
        # Extract content from response API format
        if hasattr(response, "output") and response.output:
            content = (
                response.output[0].content[0].text
                if response.output[0].content
                else None
            )
        else:
            content = None

        if content is None:
            raise ValueError("OpenAI Codex response content is None")

        result = str(content)
        self._add_output_tokens(result)
        return result


# ----------------------------
# Ollama Client Implementation
# ----------------------------
class OllamaClient(LLMClient):
    def __init__(
        self,
        model: str,
        max_output_tokens: Optional[int] = None,
        enable_token_limit: bool = False,
        **kwargs: Any,
    ) -> None:
        super().__init__(model, max_output_tokens, enable_token_limit)
        import ollama

        self.ollama = ollama

    def generate(self, prompt: str, **kwargs: Any) -> str:
        response = self.ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            **kwargs,
        )
        content = response["message"]["content"]
        if not isinstance(content, str):
            raise ValueError(f"Expected string content, got {type(content)}")

        self._add_output_tokens(content)
        return content


# ----------------------------
# Factory Function (Optional)
# ----------------------------
def create_llm_client(
    provider: str,
    model: str,
    max_output_tokens: Optional[int] = None,
    enable_token_limit: Optional[bool] = None,
    **kwargs: Any,
) -> LLMClient:
    """Create an LLM client with the specified provider and configuration.

    Args:
        provider: The LLM provider ('openai', 'openai-codex', or 'ollama').
        model: The model identifier.
        max_output_tokens: Maximum number of output tokens allowed (default: 1M).
        enable_token_limit: Whether to enforce the token limit. If None, uses provider defaults:
                          - OpenAI clients: True (limits enabled by default)
                          - Ollama clients: False (limits disabled by default)
        **kwargs: Additional provider-specific arguments.

    Returns:
        Configured LLM client instance.

    Raises:
        ValueError: If the provider is not supported.
    """
    provider = provider.lower()

    # Extract token limit parameters from kwargs to pass to constructors
    client_kwargs = {
        k: v
        for k, v in kwargs.items()
        if k not in ["max_output_tokens", "enable_token_limit"]
    }

    client: LLMClient
    if provider == "openai":
        # OpenAI default: token limits enabled
        limit_enabled = True if enable_token_limit is None else enable_token_limit
        client = OpenAIClient(model, max_output_tokens, limit_enabled, **client_kwargs)
    elif provider == "openai-codex":
        # OpenAI Codex default: token limits enabled
        limit_enabled = True if enable_token_limit is None else enable_token_limit
        client = OpenAICodexClient(
            model, max_output_tokens, limit_enabled, **client_kwargs
        )
    elif provider == "ollama":
        # Ollama default: token limits disabled
        limit_enabled = False if enable_token_limit is None else enable_token_limit
        client = OllamaClient(model, max_output_tokens, limit_enabled, **client_kwargs)
    else:
        raise ValueError(f"Unsupported provider: {provider}")

    return client
