initial_prior: 0.5
initial_population_size: 1
max_population_size: 15
offspring_rate: 0.2
elitism_rate: 1.0

alpha: 0.05
beta: 0.3
gamma: 0.25
learning_rate: 0.1

cpu_workers: 8
num_inputs: 60

adversarial_refiner_rate: 1.0
noop_rate: 0.0
